### ISSUE TITLE
cra-fork

### ISSUE THREAD

**Issue by alistair-hmh** [MikeSuiter/cra2-alpha-yarn-workspace#1]
When I run your code I get...

```shell
 yarn start
yarn run v1.12.3
$ lerna run --parallel start
lerna notice cli v3.4.3
lerna info Executing command in 2 packages: "yarn run start"
@company/app-shared: $ react-scripts start
@company/app-standalone: $ react-scripts start
@company/app-standalone: Yarn Workspaces paths detected.
@company/app-shared: Yarn Workspaces paths detected.
@company/app-standalone: Found 2 path(s) with "main:src" entry.
@company/app-shared: Found 2 path(s) with "main:src" entry.
@company/app-shared: Exporting Workspaces config to Webpack.
@company/app-standalone: Exporting Workspaces config to Webpack.
@company/app-standalone: { root: '/Users/macdonalda/repos/cra2-alpha-yarn-workspace',
@company/app-standalone:   paths:
@company/app-standalone:    [ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
@company/app-standalone:      '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ],
@company/app-standalone:   packageEntry: 'main:src',
@company/app-standalone:   development: true,
@company/app-standalone:   production: true }
@company/app-standalone: [ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
@company/app-standalone:   '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ]
@company/app-shared: { root: '/Users/macdonalda/repos/cra2-alpha-yarn-workspace',
@company/app-shared:   paths:
@company/app-shared:    [ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
@company/app-shared:      '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ],
@company/app-shared:   packageEntry: 'main:src',
@company/app-shared:   development: true,
@company/app-shared:   production: true }
@company/app-shared: [ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
@company/app-shared:   '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ]
@company/app-standalone: Starting the development server...
@company/app-shared: events.js:167
@company/app-shared:       throw er; // Unhandled 'error' event
@company/app-shared:       ^
@company/app-shared: Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
@company/app-shared:     at Server.setupListenHandle [as _listen2] (net.js:1290:14)
@company/app-shared:     at listenInCluster (net.js:1338:12)
@company/app-shared:     at doListen (net.js:1469:7)
@company/app-shared:     at process.internalTickCallback (internal/process/next_tick.js:72:19)
@company/app-shared: Emitted 'error' event at:
@company/app-shared:     at emitErrorNT (net.js:1317:8)
@company/app-shared:     at process.internalTickCallback (internal/process/next_tick.js:72:19)
@company/app-shared: error Command failed with exit code 1.
@company/app-shared: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in '@company/app-shared'
lerna ERR! yarn run start stdout:
$ react-scripts start
Yarn Workspaces paths detected.
Found 2 path(s) with "main:src" entry.
Exporting Workspaces config to Webpack.
{ root: '/Users/macdonalda/repos/cra2-alpha-yarn-workspace',
  paths:
   [ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
     '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ],
  packageEntry: 'main:src',
  development: true,
  production: true }
[ '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/core/src',
  '/Users/macdonalda/repos/cra2-alpha-yarn-workspace/packages/shared/src' ]
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run start stderr:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at doListen (net.js:1469:7)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1317:8)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
error Command failed with exit code 1.

lerna ERR! yarn run start exited 1 in '@company/app-shared'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by alistair-hmh** [comment]
Perhaps this depends on the effectiveness of NWB... but I was wondering how valuable a Create-React-App with monorepo support is to you/your company?

It's valuable to mine right now.

I'm asking because if CRA stall indefinitely on NWB recommendations, maybe we should collaborate on a long-lived fork of create-react-app and react-scripts for our engineers to use.

**Comment by MikeSuiter** [comment]
@alistair-hmh Monorepo support is very important to us as we'll have a handful off apps that will shared a lot of common code. We'll also have some customers that will customize our apps and also use our common code. 

It would be nice if someone from the CRA team would post an update letting everyone know what and when their plans are. If excellent documentation is coming in 2 weeks for CRA monorepos then I could hold off. If they have no idea then your suggestion of a react-scripts fork might be the way to go.

**Comment by MikeSuiter** [comment]
This is what app-shared should look like.

![image](https://user-images.githubusercontent.com/5289509/48715833-8a922980-ebdb-11e8-94a9-baf5992dc043.png)

**Comment by alistair-hmh** [comment]
I would have thought you'd have to reinstall everything in yarn from the base of the monorepo due to hoisting. I will double check things here in a few mins.

**Comment by MikeSuiter** [comment]
> I would have thought you'd have to reinstall everything in yarn from the base of the monorepo due to hoisting. I will double check things here in a few mins.

`yarn reset:all` should do that. 

```
    "clean:all": "lerna clean --yes && rimraf yarn.lock && rimraf node_modules/*",
    "reset:all": "yarn run clean:all && yarn",
```

**Comment by alistair-hmh** [comment]
ah, ok - testing here

**Comment by alistair-hmh** [comment]
## Steps (Working here)

Lerna init

```shell
cd ~/repos
mkdir rs-test-1
cd rs-test-1

lerna init
```

Update package.json

```json
{
  "name": "root",
  "private": true,
  "devDependencies": {
    "lerna": "^3.4.0"
  },
  "workspaces": [
    "packages/apps/*",
    "packages/components/*"
  ]
}
```

```shell
# Make some package dirs
cd packages
mkdir apps
mkdir components

# create react app (custom-script)
cd apps
create-react-app --scripts-version @f1lt3r/react-scripts@2.1.1-zeta-001 app-foo

# check the app runs
cd app-foo
yarn start

# check we have workspaces support
tree ../../../node_modules/@f1lt3r/react-scripts/config
# ../../../node_modules/@f1lt3r/react-scripts/config
# ├── env.js
# ├── jest
# │   ├── babelTransform.js
# │   ├── cssTransform.js
# │   └── fileTransform.js
# ├── paths.js
# ├── webpack.config.js
# ├── webpackDevServer.config.js
# └── workspaces.js
# 
# 1 directory, 8 files


cd ../../components
mkdir comp-one
cd comp-one
```

package.json:

```json
{
    "name": "@project/comp-one",
    "version": "1.0.0",
    "main:src": "src/index.js"
}
```

```shell
mkdir src
cd src
```

src/index.js:

```js
import React from 'react';

const CompOne = () => <div>
    <h3>CompOne</h3>
    <p><i>Transpiled On-The-Fly</i></p>
    <code>&#123;"main:src": "src/index.js"&#125;</code>
</div>;

export default CompOne;
```

```shell
cd ../../apps/app-foo
```

package.json

```json
{
  "name": "app-foo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@f1lt3r/react-scripts": "2.1.1-zeta-001",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "@project/comp-one": "1.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

src/App.js:

```js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import CompOne from '@project/comp-one';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          <CompOne />
        </header>
      </div>
    );
  }
}

export default App;
```

```shell
cd ~/repos/rs-test-1
```

lerna.json:

```json
{
  "version": "1.0.0",
  "useWorkspaces": true
}
```

```shell
# relink and build fresh packages
cd ~/repos/rs-test-1
yarn
```

# restart app
cd packages/apps/
yarn start
```

## Result

- Component showing as expected.
- Hot reloading working.

<img width="1440" alt="screen shot 2018-11-19 at 11 41 22 am" src="https://user-images.githubusercontent.com/38665769/48721651-5d9c4180-ebf0-11e8-96a5-70ccfa853aab.png">

**Comment by alistair-hmh** [comment]
So @MikeSuiter - I'm wondering if your `<workspaces-root>/package.json` lists your workspaces? If so... everything should work without configuration.

**Comment by MikeSuiter** [comment]
> So @MikeSuiter - I'm wondering if your `<workspaces-root>/package.json` lists your workspaces? If so... everything should work without configuration.

It does - https://github.com/MikeSuiter/cra2-alpha-yarn-workspace/blob/cra-fork/package.json

**Comment by alistair-hmh** [comment]
So I'm running your code... should I expect to see 2 apps start in the browser?

Running you code always gives me a message that an existing app is running, and asks if I want to run on different port.

**Comment by alistair-hmh** [comment]
FWIW: if I `yarn` your codebase, I have both:

1. <workspaces_root>/node_modules/react-scripts/
2. <workspaces_root>/node_modules/@f1lt3r/react-scripts/

In my codebase I only have:

1. <workspaces_root>/node_modules/@f1lt3r/react-scripts

**Comment by MikeSuiter** [comment]
I'll look at my code again now.

For simplicity I would just run `yarn start` from `apps/app-shared`.

**Comment by MikeSuiter** [comment]
I found react-scripts in one of my packages and removed it but still get the same error. I committed the change.

**Comment by MikeSuiter** [comment]
Had to update my imports and everything is work now. I've committed all my changes.

`import Header from '@company/core/src/components/Header';`

**Comment by alistair-hmh** [comment]
It looks odd to me that you're importing `src/` - but perhaps that's  convention that works for your use-case.

**Comment by alistair-hmh** [comment]
In your use-case, will your components ever be published independently on an Npm registry (public or private)?

**Comment by MikeSuiter** [comment]
Our app is pretty big (close to 500 JavaScript files) and being a CRA app everything of course is currently under src so our imports look like this:

```
import Loader from 'components/Loader/index';
import ActionToolbar from 'containers/ActionToolbar/index';
import PagingToolbar from 'containers/PagingToolbar/index';
```

Going to a workspace moving most of the code to packages it would take a lot of work putting an index.js at the root and probably needing a bunch below it so it would be nice to do something like:

```
import Loader from '@company/common/components/Loader/index';
import ActionToolbar from '@company/common/containers/ActionToolbar/index';
import PagingToolbar from '@company/common/containers/PagingToolbar/index';
```

To do this using your react-scripts fork, since it requires `"main:src": "src/index.js"` I had to put /src in the imports. If you looks at the index.js for this cra-fork they are actually blank.

Our components will never be published private or public - they will always be used as source code.

**Comment by MikeSuiter** [comment]
@alistair-hmh just wondering if you've done any more work or found a great solution for working with monorepos with CRA2? I took a break from it including moving our forms from redux-form to Formik but was hoping we would hear something from the CRA team by now. We have a solution but not being able to debug source code in packages really stinks. 

My last post in the long-running CRA monorepo thread did get a lot of reactions.

https://github.com/facebook/create-react-app/issues/1333#issuecomment-439937660

**Comment by alistair-hmh** [comment]
Extending CRA to support Workspaces with the `--scripts-version` flag has been working fine for us. We're in the process of putting about 8 apps into this structure.

So far, so good.

https://github.com/F1LT3R/cra-workspaces-poc

**Comment by MikeSuiter** [comment]
@alistair-hmh I updated the cra-fork branch here to use your latest @f1lt3r/react-scripts and things are looking good. My POC closely matches the tools we currently use and 2 things I've encountered.

1. Running `yarn start` in apps/app-shared doesn't show lint warnings from code in packages/*
2. Running 'yarn analyze` in apps/app-shared doesn't work because you don't have a webpack.config.prod. Here is the error:
`Error: Cannot find module '@f1lt3r/react-scripts/config/webpack.config.prod'`

If you want to discuss what we're doing and requirements I can contact you using the email on your profile. I appreciate your work on CRA monorepo support.

**Comment by MikeSuiter** [comment]
I'm using your fork for react-scripts (which is the CRA version) and Yarn 1.12.3

**Comment by alistair-hmh** [comment]
Doesn't the latest react-scripts use a single config for both dev and prod?

**Comment by alistair-hmh** [comment]
Linting is working for me. (I think)

Would you expect to see something more than these...

CLI

![screen shot 2018-12-20 at 9 13 02 am](https://user-images.githubusercontent.com/38665769/50289704-991c6c80-0437-11e9-88dc-591ae47d1849.png)

Browser

![screen shot 2018-12-20 at 9 13 20 am](https://user-images.githubusercontent.com/38665769/50289703-991c6c80-0437-11e9-8d3d-96e57b5ea670.png)

**Comment by MikeSuiter** [comment]
> Doesn't the latest react-scripts use a single config for both dev and prod?

No my 2.1.1 has a dev and prod.

![image](https://user-images.githubusercontent.com/5289509/50290535-99b20480-0431-11e9-9285-b08854e82d5a.png)

> Linting is working for me. (I think)

I just made these changes to your cra-workspaces-poc and see lint errors under apps/app-foo but not under components/comp-one.

App.js
```
class App extends Component {
    render() {
        const unused = true;

        return (
```

index.js (CompOne)
```
const CompOne = () => {
    const unused = true;

    return <div>
```

CLI
![image](https://user-images.githubusercontent.com/5289509/50291280-bd764a00-0433-11e9-8515-2bb1c8708fa0.png)

Browser
![image](https://user-images.githubusercontent.com/5289509/50291309-cf57ed00-0433-11e9-9a3a-398c91e9e37f.png)

**Comment by MikeSuiter** [comment]
@alistair-hmh I just pushed updates to the cra-fork branch on this repo which has the same lint test as above and also has the analyze script back to how it works with react-scripts 2.1.1.

**Comment by alistair-hmh** [comment]
@MikeSuiter I'm not sure how you're getting the two different Webpack configs. Here is what I see:

![screen shot 2018-12-21 at 9 07 50 am](https://user-images.githubusercontent.com/38665769/50346314-ff6cc200-04ff-11e9-82be-c4a1c4eb4291.png)

I wonder if you built your react apps without using `create-react-app --scripts-version @f1lt3r/react-scripts app-foo`?

You're right about linting though, I don't see lint errors in my `comp-one` component. I do see JavaScript errors. I'll look into this.

**Comment by alistair-hmh** [comment]
Got it working:

![screen shot 2018-12-21 at 9 16 49 am](https://user-images.githubusercontent.com/38665769/50346715-3394b280-0501-11e9-9071-3f95a9bdf0c1.png)
![screen shot 2018-12-21 at 9 16 42 am](https://user-images.githubusercontent.com/38665769/50346716-3394b280-0501-11e9-9d39-13b3c4fc010c.png)

I'll update the custom react-scripts and let you know when that is done.

**Comment by alistair-hmh** [comment]
Should work now. 

Update your `react-scripts` version in your app's `package.json` to:

```json
{
	"dependancies": {
		"@f1lt3r/react-scripts": "@2.1.1-monorepo-02"
	}
}
```

Then `yarn`

**Comment by MikeSuiter** [comment]
@alistair-hmh I updated and the package linting works - thanks a ton!

The core react-scripts have both a `webpack.config.dev.js` and `webpack.config.prod.js` in the config folder. Your react-scripts only has `webpack.config.js`. I changed (but didn't commit) my scripts/analyzeBuild.js to use your scripts:

```javascript
// to use run: node analyzeBuild.js

// eslint-disable-next-line prefer-destructuring
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

process.env.NODE_ENV = 'production';

const webpackConfigProd = require('@f1lt3r/react-scripts/config/webpack.config');

webpackConfigProd.plugins.push(
  new BundleAnalyzerPlugin({
    analyzerMode: 'static',
    reportFilename: 'report.html'
  })
);

require('@f1lt3r/react-scripts/scripts/build');
```

but it doesn't like it.
```log
D:\Workspaces\React\cra2-alpha-yarn-workspace\apps\app-shared\scripts\analyzeBuild.js:10
webpackConfigProd.plugins.push(
                          ^

TypeError: Cannot read property 'push' of undefined
    at Object.<anonymous> (D:\Workspaces\React\cra2-alpha-yarn-workspace\apps\app-shared\scripts\analyzeBuild.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
```

**Comment by alistair-hmh** [comment]
Just about to take off for the holidays so I won't be able to dig into analyzer until next year. I'll be back the second week of Jan.

FWIW: I wonder if investigating why you have prod and dev configs, and I don't, may lead you to why configProd has no plugins property.

**Comment by MikeSuiter** [comment]
@alistair-hmh Hope you had a good break over the holidays. I'm actually trying your CRA fork in our real project and so far it's good. Still have the analyze script problem which would love to work with you to get working. Might even be better to use email or Slack to discuss things if you want.
